import type { NextConfig } from "next";

// Cache bust: 20260530
const nextConfig: NextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '**.supabase.co' },
    ],
  },
  async redirects() {
    return [
      // /ko → / (no Korean sub-path exists; handles old links and crawlers)
      { source: '/ko', destination: '/', permanent: true },
      { source: '/ko/:path*', destination: '/:path*', permanent: true },
      // Duplicate content 301 redirects
      { source: '/blog/cosmetics-pharmaceutical-license-guide', destination: '/blog/cosmetics-responsible-distributor', permanent: true },
      { source: '/blog/venture-vs-innobiz-comparison-guide', destination: '/blog/venture-innobiz-certification-guide', permanent: true },
      { source: '/blog/corporate-rnd-center-requirements-2026', destination: '/blog/corporate-research-lab-establishment-guide', permanent: true },
      { source: '/blog/freight-forwarder-capital-bond', destination: '/blog/international-logistics-capital-funding-guide', permanent: true },
      { source: '/blog/currency-exchange-registration', destination: '/blog/currency-exchange-registration-guide', permanent: true },
      { source: '/blog/hostel-registration-facility', destination: '/blog/hostel-registration-guide', permanent: true },
      { source: '/blog/foreigner-urban-homestay-registration', destination: '/blog/urban-guesthouse-registration-guide', permanent: true },
      { source: '/blog/hanok-stay-registration-requirements', destination: '/blog/hanok-experience-registration-guide', permanent: true },
      { source: '/blog/nonprofit-association-permit', destination: '/blog/nonprofit-corporation-establishment-guide', permanent: true },
      { source: '/blog/tobacco-import-registration', destination: '/blog/tobacco-import-sales-guide', permanent: true },
      { source: '/blog/e-cigarette-import-permit', destination: '/blog/e-cigarette-import-license-guide', permanent: true },
      { source: '/blog/women-owned-business-certification', destination: '/blog/women-enterprise-certification-guide', permanent: true },
      { source: '/blog/g2b-registration-procedure', destination: '/blog/procurement-narajangteo-registration-guide', permanent: true },
      // Blog date-cleanup 301s (slug date suffixes removed; near-duplicate topics consolidated to one representative post)
      { source: '/blog/hagwon-establishment-registration-202605', destination: '/blog/hagwon-establishment-registration', permanent: true },
      { source: '/blog/hagwon-establishment-registration-202606', destination: '/blog/hagwon-establishment-registration', permanent: true },
      { source: '/blog/hagwon-establishment-registration-202607', destination: '/blog/hagwon-establishment-registration', permanent: true },
      { source: '/blog/hagwon-establishment-registration-202608', destination: '/blog/hagwon-establishment-registration', permanent: true },
      { source: '/blog/hagwon-establishment-registration-202609', destination: '/blog/hagwon-establishment-registration', permanent: true },
      { source: '/blog/rest-restaurant-notification-202605', destination: '/blog/rest-restaurant-notification', permanent: true },
      { source: '/blog/rest-restaurant-notification-202606', destination: '/blog/rest-restaurant-notification', permanent: true },
      { source: '/blog/rest-restaurant-notification-202607', destination: '/blog/rest-restaurant-notification', permanent: true },
      { source: '/blog/rest-restaurant-notification-202608', destination: '/blog/rest-restaurant-notification', permanent: true },
      { source: '/blog/rest-restaurant-notification-202609', destination: '/blog/rest-restaurant-notification', permanent: true },
      { source: '/blog/accommodation-business-registration-202605', destination: '/blog/accommodation-business-registration', permanent: true },
      { source: '/blog/accommodation-business-registration-202606', destination: '/blog/accommodation-business-registration', permanent: true },
      { source: '/blog/accommodation-business-registration-202607', destination: '/blog/accommodation-business-registration', permanent: true },
      { source: '/blog/accommodation-business-registration-202608', destination: '/blog/accommodation-business-registration', permanent: true },
      { source: '/blog/accommodation-business-registration-202609', destination: '/blog/accommodation-business-registration', permanent: true },
      { source: '/blog/medical-device-import-permit-20260527', destination: '/blog/medical-device-import-permit', permanent: true },
      { source: '/blog/medical-device-import-permit-2026-06-05', destination: '/blog/medical-device-import-permit', permanent: true },
      { source: '/blog/food-import-sales-registration-20260527', destination: '/blog/food-import-sales-registration', permanent: true },
      { source: '/blog/venture-certification-renewal-20260527', destination: '/blog/venture-certification-renewal', permanent: true },
      { source: '/blog/haccp-mandatory-industries-2026', destination: '/blog/haccp-mandatory-industries', permanent: true },
      { source: '/blog/g2b-direct-production-renewal-2026', destination: '/blog/g2b-direct-production-renewal', permanent: true },
      { source: '/blog/restaurant-permit-checklist-2026', destination: '/blog/restaurant-permit-checklist', permanent: true },
      { source: '/blog/cleaning-business-report-2026', destination: '/blog/cleaning-business-report', permanent: true },
      { source: '/blog/real-estate-agency-registration-2026', destination: '/blog/real-estate-agency-registration', permanent: true },
      { source: '/blog/liquor-sales-license-20260530', destination: '/blog/liquor-sales-license', permanent: true },
      { source: '/blog/health-functional-food-registration-20260530', destination: '/blog/health-functional-food-registration', permanent: true },
      { source: '/blog/travel-agency-registration-20260530', destination: '/blog/travel-agency-registration', permanent: true },
      { source: '/blog/medical-device-sales-registration-20260531', destination: '/blog/medical-device-sales-registration', permanent: true },
      { source: '/blog/pesticide-sales-registration-20260531', destination: '/blog/pesticide-sales-registration', permanent: true },
      { source: '/blog/environmental-facility-permit-20260531', destination: '/blog/environmental-facility-permit', permanent: true },
      { source: '/blog/public-hygiene-business-permit-20260601', destination: '/blog/public-hygiene-business-permit', permanent: true },
      { source: '/blog/gas-station-dangerous-goods-permit-20260601', destination: '/blog/gas-station-dangerous-goods-permit', permanent: true },
      { source: '/blog/waste-treatment-permit-20260601', destination: '/blog/waste-treatment-permit', permanent: true },
      { source: '/blog/food-manufacturing-permit-2026-06-03', destination: '/blog/food-manufacturing-permit', permanent: true },
      { source: '/blog/karaoke-business-report-2026-06-03', destination: '/blog/karaoke-business-report', permanent: true },
      { source: '/blog/real-estate-brokerage-registration-2026-06-03', destination: '/blog/real-estate-brokerage-registration', permanent: true },
      { source: '/blog/academy-establishment-registration-2026-06-04', destination: '/blog/academy-establishment-registration', permanent: true },
      { source: '/blog/accommodation-business-report-2026-06-04', destination: '/blog/accommodation-business-report', permanent: true },
      { source: '/blog/game-providing-business-permit-2026-06-04', destination: '/blog/game-providing-business-permit', permanent: true },
      { source: '/blog/karaoke-business-facility-report-2026-06-05', destination: '/blog/karaoke-business-facility-report', permanent: true },
      { source: '/blog/online-shopping-mall-notification-2026-06-05', destination: '/blog/online-shopping-mall-notification', permanent: true },
      { source: '/blog/building-use-change-permit-2026-06-06', destination: '/blog/building-use-change-permit', permanent: true },
      { source: '/blog/fire-safety-contractor-registration-2026-06-06', destination: '/blog/fire-safety-contractor-registration', permanent: true },
      { source: '/blog/rnd-service-business-registration-2026-06-06', destination: '/blog/rnd-service-business-registration', permanent: true },
      { source: '/blog/real-estate-development-registration-2026-06-07', destination: '/blog/real-estate-development-registration', permanent: true },
      { source: '/blog/pharmaceutical-wholesale-license-2026-06-07', destination: '/blog/pharmaceutical-wholesale-license', permanent: true },
      { source: '/blog/venture-startup-confirmation-2026-06-07', destination: '/blog/venture-startup-confirmation', permanent: true },
      { source: '/blog/food-business-hygiene-permit-2026-06-08', destination: '/blog/food-business-hygiene-permit', permanent: true },
      { source: '/blog/cosmetics-manufacturing-permit-2026-06-08', destination: '/blog/cosmetics-manufacturing-permit', permanent: true },
      { source: '/blog/waste-collection-transport-permit-2026-06-08', destination: '/blog/waste-collection-transport-permit', permanent: true },
    ]
  },
};

export default nextConfig;
