// Blog slugs that 301 elsewhere. Single source of truth for BOTH next.config.ts redirects()
// and app/sitemap.ts — a redirect source must never be listed in the sitemap (GSC: "Page with redirect").
export const BLOG_REDIRECTS: ReadonlyArray<{ source: string; destination: string }> = [
  { source: '/blog/cosmetics-pharmaceutical-license-guide', destination: '/blog/cosmetics-responsible-distributor' },
  { source: '/blog/venture-vs-innobiz-comparison-guide', destination: '/blog/venture-innobiz-certification-guide' },
  { source: '/blog/corporate-rnd-center-requirements-2026', destination: '/blog/corporate-research-lab-establishment-guide' },
  { source: '/blog/freight-forwarder-capital-bond', destination: '/blog/international-logistics-capital-funding-guide' },
  { source: '/blog/currency-exchange-registration', destination: '/blog/currency-exchange-registration-guide' },
  { source: '/blog/hostel-registration-facility', destination: '/blog/hostel-registration-guide' },
  { source: '/blog/foreigner-urban-homestay-registration', destination: '/blog/urban-guesthouse-registration-guide' },
  { source: '/blog/hanok-stay-registration-requirements', destination: '/blog/hanok-experience-registration-guide' },
  { source: '/blog/nonprofit-association-permit', destination: '/blog/nonprofit-corporation-establishment-guide' },
  { source: '/blog/tobacco-import-registration', destination: '/blog/tobacco-import-sales-guide' },
  { source: '/blog/e-cigarette-import-permit', destination: '/blog/e-cigarette-import-license-guide' },
  { source: '/blog/women-owned-business-certification', destination: '/blog/women-enterprise-certification-guide' },
  { source: '/blog/g2b-registration-procedure', destination: '/blog/procurement-narajangteo-registration-guide' },
  { source: '/blog/hagwon-establishment-registration-202605', destination: '/blog/hagwon-establishment-registration' },
  { source: '/blog/hagwon-establishment-registration-202606', destination: '/blog/hagwon-establishment-registration' },
  { source: '/blog/hagwon-establishment-registration-202607', destination: '/blog/hagwon-establishment-registration' },
  { source: '/blog/hagwon-establishment-registration-202608', destination: '/blog/hagwon-establishment-registration' },
  { source: '/blog/hagwon-establishment-registration-202609', destination: '/blog/hagwon-establishment-registration' },
  { source: '/blog/rest-restaurant-notification-202605', destination: '/blog/rest-restaurant-notification' },
  { source: '/blog/rest-restaurant-notification-202606', destination: '/blog/rest-restaurant-notification' },
  { source: '/blog/rest-restaurant-notification-202607', destination: '/blog/rest-restaurant-notification' },
  { source: '/blog/rest-restaurant-notification-202608', destination: '/blog/rest-restaurant-notification' },
  { source: '/blog/rest-restaurant-notification-202609', destination: '/blog/rest-restaurant-notification' },
  { source: '/blog/accommodation-business-registration-202605', destination: '/blog/accommodation-business-registration' },
  { source: '/blog/accommodation-business-registration-202606', destination: '/blog/accommodation-business-registration' },
  { source: '/blog/accommodation-business-registration-202607', destination: '/blog/accommodation-business-registration' },
  { source: '/blog/accommodation-business-registration-202608', destination: '/blog/accommodation-business-registration' },
  { source: '/blog/accommodation-business-registration-202609', destination: '/blog/accommodation-business-registration' },
  { source: '/blog/medical-device-import-permit-20260527', destination: '/blog/medical-device-import-permit' },
  { source: '/blog/medical-device-import-permit-2026-06-05', destination: '/blog/medical-device-import-permit' },
  { source: '/blog/food-import-sales-registration-20260527', destination: '/blog/food-import-sales-registration' },
  { source: '/blog/venture-certification-renewal-20260527', destination: '/blog/venture-certification-renewal' },
  { source: '/blog/haccp-mandatory-industries-2026', destination: '/blog/haccp-mandatory-industries' },
  { source: '/blog/g2b-direct-production-renewal-2026', destination: '/blog/g2b-direct-production-renewal' },
  { source: '/blog/restaurant-permit-checklist-2026', destination: '/blog/restaurant-permit-checklist' },
  { source: '/blog/cleaning-business-report-2026', destination: '/blog/cleaning-business-report' },
  { source: '/blog/real-estate-agency-registration-2026', destination: '/blog/real-estate-agency-registration' },
  { source: '/blog/liquor-sales-license-20260530', destination: '/blog/liquor-sales-license' },
  { source: '/blog/health-functional-food-registration-20260530', destination: '/blog/health-functional-food-registration' },
  { source: '/blog/travel-agency-registration-20260530', destination: '/blog/travel-agency-registration' },
  { source: '/blog/medical-device-sales-registration-20260531', destination: '/blog/medical-device-sales-registration' },
  { source: '/blog/pesticide-sales-registration-20260531', destination: '/blog/pesticide-sales-registration' },
  { source: '/blog/environmental-facility-permit-20260531', destination: '/blog/environmental-facility-permit' },
  { source: '/blog/public-hygiene-business-permit-20260601', destination: '/blog/public-hygiene-business-permit' },
  { source: '/blog/gas-station-dangerous-goods-permit-20260601', destination: '/blog/gas-station-dangerous-goods-permit' },
  { source: '/blog/waste-treatment-permit-20260601', destination: '/blog/waste-treatment-permit' },
  { source: '/blog/food-manufacturing-permit-2026-06-03', destination: '/blog/food-manufacturing-permit' },
  { source: '/blog/karaoke-business-report-2026-06-03', destination: '/blog/karaoke-business-report' },
  { source: '/blog/real-estate-brokerage-registration-2026-06-03', destination: '/blog/real-estate-brokerage-registration' },
  { source: '/blog/academy-establishment-registration-2026-06-04', destination: '/blog/academy-establishment-registration' },
  { source: '/blog/accommodation-business-report-2026-06-04', destination: '/blog/accommodation-business-report' },
  { source: '/blog/game-providing-business-permit-2026-06-04', destination: '/blog/game-providing-business-permit' },
  { source: '/blog/karaoke-business-facility-report-2026-06-05', destination: '/blog/karaoke-business-facility-report' },
  { source: '/blog/online-shopping-mall-notification-2026-06-05', destination: '/blog/online-shopping-mall-notification' },
  { source: '/blog/building-use-change-permit-2026-06-06', destination: '/blog/building-use-change-permit' },
  { source: '/blog/fire-safety-contractor-registration-2026-06-06', destination: '/blog/fire-safety-contractor-registration' },
  { source: '/blog/rnd-service-business-registration-2026-06-06', destination: '/blog/rnd-service-business-registration' },
  { source: '/blog/real-estate-development-registration-2026-06-07', destination: '/blog/real-estate-development-registration' },
  { source: '/blog/pharmaceutical-wholesale-license-2026-06-07', destination: '/blog/pharmaceutical-wholesale-license' },
  { source: '/blog/venture-startup-confirmation-2026-06-07', destination: '/blog/venture-startup-confirmation' },
  { source: '/blog/food-business-hygiene-permit-2026-06-08', destination: '/blog/food-business-hygiene-permit' },
  { source: '/blog/cosmetics-manufacturing-permit-2026-06-08', destination: '/blog/cosmetics-manufacturing-permit' },
  { source: '/blog/waste-collection-transport-permit-2026-06-08', destination: '/blog/waste-collection-transport-permit' },

  // ── GSC 404 정리 (2026-09-17, 맥7 지시) ──────────────────────────────
  // 사이트 재구축 전 옛 블로그 slug. 대응 canonical 이 라이브 200 인 것만 매핑했다.
  { source: '/blog/2026-05-24-laundry-business-registration', destination: '/blog/laundry-business-permit-guide' },
  { source: '/blog/beauty-salon-business-registration-guide', destination: '/blog/beauty-salon-notification-guide' },
  { source: '/blog/building-use-change-cost-and-duration', destination: '/blog/building-usage-change-guide' },
  { source: '/blog/building-use-change-guide', destination: '/blog/building-usage-change-guide' },
  { source: '/blog/building-use-change-permit-required-documents', destination: '/blog/building-use-change-permit-guide' },
  { source: '/blog/city-homestay-registration', destination: '/blog/urban-guesthouse-registration-guide' },
  { source: '/blog/corporate-research-institute-setup-guide', destination: '/blog/corporate-research-lab-establishment-guide' },
  { source: '/blog/currency-exchange-business-registration-guide', destination: '/blog/currency-exchange-registration-guide' },
  { source: '/blog/factory-registration-complete-guide-2026', destination: '/blog/factory-registration-application-guide' },
  { source: '/blog/food-manufacturing-business-report-steps', destination: '/blog/food-manufacturing-license-guide' },
  { source: '/blog/food-manufacturing-facility-standards-guide', destination: '/blog/food-manufacturing-license-guide' },
  { source: '/blog/food-manufacturing-registration-guide-2026', destination: '/blog/food-manufacturing-license-guide' },
  { source: '/blog/food-manufacturing-registration-requirements', destination: '/blog/food-manufacturing-license-guide' },
  { source: '/blog/game-room-business-registration-guide', destination: '/blog/game-providing-business-permit' },
  { source: '/blog/haccp-certification-complete-guide', destination: '/blog/haccp-certification-guide' },
  { source: '/blog/haccp-certification-full-process', destination: '/blog/haccp-certification-guide' },
  { source: '/blog/haccp-certification-steps-guide', destination: '/blog/haccp-certification-guide' },
  { source: '/blog/haccp-certification-walkthrough', destination: '/blog/haccp-certification-guide' },
  { source: '/blog/haccp-mandatory-voluntary', destination: '/blog/haccp-mandatory-industries' },
  { source: '/blog/hagwon-establishment-registration-guide', destination: '/blog/hagwon-establishment-registration' },
  { source: '/blog/hakwon-establishment-guide-2026', destination: '/blog/hagwon-establishment-registration' },
  { source: '/blog/hakwon-seolrip-2026', destination: '/blog/hagwon-establishment-registration' },
  { source: '/blog/hostel-business-registration-guide', destination: '/blog/hostel-registration-guide' },
  { source: '/blog/international-freight-forwarding-registration', destination: '/blog/international-logistics-registration-guide' },
  { source: '/blog/international-logistics-forwarder-capital-requirements', destination: '/blog/freight-forwarder-capital-bond-requirements' },
  { source: '/blog/laundry-business-permit-2026-06-02', destination: '/blog/laundry-business-permit-guide' },
  { source: '/blog/laundry-business-registration-guide', destination: '/blog/laundry-business-permit-guide' },
  { source: '/blog/laundry-business-registration-guide-2026', destination: '/blog/laundry-business-permit-guide' },
  { source: '/blog/neighborhood-facility-use-change-conditions', destination: '/blog/building-usage-change-case-studies-guide' },
  { source: '/blog/nonprofit-corporation-setup', destination: '/blog/nonprofit-corporation-establishment-guide' },
  { source: '/blog/private-academy-registration-guide', destination: '/blog/hagwon-establishment-registration' },
  { source: '/blog/public-bath-business-permit-guide', destination: '/blog/public-hygiene-business-permit' },
  { source: '/blog/restaurant-permit-vs-report-guide', destination: '/blog/restaurant-food-service-license-guide' },
  { source: '/blog/sikpum-jejo-2026', destination: '/blog/food-manufacturing-license-guide' },
  { source: '/blog/small-food-manufacturing-license', destination: '/blog/food-manufacturing-license-guide' },
  { source: '/blog/venture-certification-requirements-application', destination: '/blog/venture-startup-confirmation' },
  { source: '/blog/women-owned-business-certification-guide', destination: '/blog/women-enterprise-certification-guide' },
]

/** Slugs that must be excluded from the sitemap because they redirect. */
export const REDIRECTED_BLOG_SLUGS: ReadonlySet<string> = new Set(
  BLOG_REDIRECTS.map((r) => r.source.replace('/blog/', ''))
)

/**
 * 서비스 페이지 정리 전의 옛 /services/<slug> 301.
 * BLOG_REDIRECTS 와 분리해 둔다 — sitemap 제외 로직(REDIRECTED_BLOG_SLUGS)은 블로그 slug 전용이다.
 */
export const SERVICE_REDIRECTS: ReadonlyArray<{ source: string; destination: string }> = [
  { source: '/services/building-usage-change', destination: '/services/building-usage' },
  { source: '/services/건축물 용도변경', destination: '/services/building-usage' },
  { source: '/services/건축물', destination: '/services/building-usage' },
  { source: '/services/식품제조가공업', destination: '/services/food-manufacturing' },
  { source: '/services/한옥체험업', destination: '/services/hanok' },
  { source: '/services/환전업 등록', destination: '/services/currency-exchange' },
  { source: '/services/환전업', destination: '/services/currency-exchange' },
  { source: '/services/rnd-center', destination: '/services/research-lab' },
  { source: '/services/sports-facility', destination: '/services/sports-club' },
  // ⚠️ 신규 mainbiz 페이지는 배포 제외(기업인증 3종 구조 확정 대기)라 이 301 을 일부러 남겨 둔다.
  //    구조 확정 후 mainbiz 를 발행하려면 이 줄을 반드시 지워야 한다 — 안 지우면 새 페이지가 렌더되지 않는다.
  { source: '/services/mainbiz', destination: '/services/venture-cert' },
  // 한글 slug 는 Next 가 퍼센트 인코딩된 pathname 으로 매칭한다 — 인코딩 판을 함께 둔다.
  { source: '/services/%EA%B1%B4%EC%B6%95%EB%AC%BC%20%EC%9A%A9%EB%8F%84%EB%B3%80%EA%B2%BD', destination: '/services/building-usage' },
  { source: '/services/%EA%B1%B4%EC%B6%95%EB%AC%BC', destination: '/services/building-usage' },
  { source: '/services/%EC%8B%9D%ED%92%88%EC%A0%9C%EC%A1%B0%EA%B0%80%EA%B3%B5%EC%97%85', destination: '/services/food-manufacturing' },
  { source: '/services/%ED%95%9C%EC%98%A5%EC%B2%B4%ED%97%98%EC%97%85', destination: '/services/hanok' },
  { source: '/services/%ED%99%98%EC%A0%84%EC%97%85%20%EB%93%B1%EB%A1%9D', destination: '/services/currency-exchange' },
  { source: '/services/%ED%99%98%EC%A0%84%EC%97%85', destination: '/services/currency-exchange' },
  // 대응 서비스가 없어진 옛 slug — 서비스 목록으로 보낸다(개별 매핑 불가).
  { source: '/services/animal', destination: '/services' },
  { source: '/services/beauty-salon', destination: '/services' },
  { source: '/services/corporation', destination: '/services' },
  { source: '/services/education', destination: '/services' },
  { source: '/services/environment', destination: '/services' },
  // (/services/factory · /services/health-food 는 2026-09-17 신규 이관으로 실제 페이지가
  //  생겼다 — 301 을 남겨 두면 Next 가 리다이렉트를 우선해 새 페이지가 절대 렌더되지 않는다.)
  { source: '/services/food-sales', destination: '/services' },
  { source: '/services/food-service', destination: '/services' },
  { source: '/services/medical', destination: '/services' },
  { source: '/services/restaurant', destination: '/services' },
  { source: '/services/sanitation', destination: '/services' },
]
