// AUTO-GENERATED by scripts/apply-i5-i4.py — I4 3종 세트 글(허브 → 선택기준·문제해결 글).
// 원본: team-relay/seo-keywords/20261002/inhega-I4. 손으로 고치지 않는다.
export const HUB_GUIDES: Record<string, { title: string; href: string }[]> = {
  "/services/building-usage": [
    {
      "title": "위반건축물 용도변경·불법 용도변경 이행강제금·처벌 정리 (건축물 용도변경 허가·신고 위반)",
      "href": "/blog/building-usage-fix"
    }
  ],
  "/services/cosmetics": [
    {
      "title": "화장품 광고 위반 행정처분·무등록 영업 처벌·변경등록 누락 취소 정리 (화장품책임판매업)",
      "href": "/blog/cosmetics-fix"
    },
    {
      "title": "화장품책임판매업 등록 대행·행정사 선택 기준 (서울·경기 관할 지방식약청)",
      "href": "/blog/cosmetics-select"
    },
    {
      "title": "기능성화장품 심사 반려 보완·인정 취소·무심사 판매 처벌 정리",
      "href": "/blog/functional-cosmetics-fix"
    },
    {
      "title": "기능성화장품 심사 대행·행정사 선택 기준과 견적·상담 시 확인할 점 (식품의약품안전평가원 심사)",
      "href": "/blog/functional-cosmetics-select"
    },
    {
      "title": "의약외품 무허가 제조·수입 처벌과 허가취소·업무정지·영업소 폐쇄 사유 정리",
      "href": "/blog/quasi-drug-fix"
    },
    {
      "title": "의약외품 허가 대행·행정사 선택 기준 (서울·경기 지방식약청 제조업 신고·품목허가)",
      "href": "/blog/quasi-drug-select"
    }
  ],
  "/services/functional-cosmetics": [
    {
      "title": "화장품 광고 위반 행정처분·무등록 영업 처벌·변경등록 누락 취소 정리 (화장품책임판매업)",
      "href": "/blog/cosmetics-fix"
    },
    {
      "title": "기능성화장품 심사 반려 보완·인정 취소·무심사 판매 처벌 정리",
      "href": "/blog/functional-cosmetics-fix"
    },
    {
      "title": "기능성화장품 심사 대행·행정사 선택 기준과 견적·상담 시 확인할 점 (식품의약품안전평가원 심사)",
      "href": "/blog/functional-cosmetics-select"
    }
  ],
  "/services/currency-exchange": [
    {
      "title": "환전업 등록 취소 사유·무등록 환전 처벌·환치기 처벌 정리",
      "href": "/blog/currency-exchange-fix"
    },
    {
      "title": "환전업 등록 대행·행정사 선택 기준 (서울·경기 영업소 관할 세관)",
      "href": "/blog/currency-exchange-select"
    }
  ],
  "/services/ecig": [
    {
      "title": "전자담배 청소년 판매 처벌·경고문구 위반·수입판매업 영업정지 정리",
      "href": "/blog/ecig-fix"
    },
    {
      "title": "전자담배 수입 허가 대행·행정사 선택 기준 (서울·경기 담배수입판매업 등록)",
      "href": "/blog/ecig-select"
    },
    {
      "title": "무등록 담배 판매 처벌·담배수입판매업 등록 취소·영업정지 사유 정리",
      "href": "/blog/tobacco-fix"
    },
    {
      "title": "담배수입판매업 등록 대행·행정사 선택 기준 (서울·경기 본점 소재지 시·도지사)",
      "href": "/blog/tobacco-select"
    }
  ],
  "/services/factory": [
    {
      "title": "공장등록 취소 사유·승인 없이 공장 설립 처벌·변경등록 누락 과태료 정리",
      "href": "/blog/factory-fix"
    },
    {
      "title": "공장등록 대행·행정사 선택 기준 (서울·경기 시·군·구청 공장등록)",
      "href": "/blog/factory-select"
    }
  ],
  "/services/food-manufacturing": [
    {
      "title": "식품제조가공업 영업정지 사유·무등록 식품제조 처벌·변경등록 누락 처분 정리",
      "href": "/blog/food-manufacturing-fix"
    },
    {
      "title": "식품제조가공업 등록 대행·행정사 선택 기준 (서울·경기 시·군·구청 등록)",
      "href": "/blog/food-manufacturing-select"
    }
  ],
  "/services/haccp": [
    {
      "title": "식품제조가공업 영업정지 사유·무등록 식품제조 처벌·변경등록 누락 처분 정리",
      "href": "/blog/food-manufacturing-fix"
    },
    {
      "title": "HACCP 인증 대행·행정사 선택 기준과 견적·상담 시 확인할 점 (식품안전관리인증기준적용업소)",
      "href": "/blog/haccp-select"
    }
  ],
  "/services/freight-trucking": [
    {
      "title": "무허가 화물운송 처벌·자가용 화물차 유상운송 처벌·허가취소 사유 정리",
      "href": "/blog/freight-trucking-fix"
    },
    {
      "title": "화물자동차 운송사업 허가 대행·행정사 선택 기준 (서울·경기 주사무소 관할 시·도지사)",
      "href": "/blog/freight-trucking-select"
    }
  ],
  "/services/hanok": [
    {
      "title": "한옥체험업 등록취소·무등록 한옥 숙박 처벌·변경등록 누락 처분 정리",
      "href": "/blog/hanok-fix"
    },
    {
      "title": "한옥체험업 등록 대행·행정사 선택 기준 (서울·경기 시·군·구청 등록)",
      "href": "/blog/hanok-select"
    }
  ],
  "/services/health-food": [
    {
      "title": "건강기능식품 수입 영업등록 취소·수입신고 위반 처벌·영업정지 사유 정리",
      "href": "/blog/health-food-fix"
    },
    {
      "title": "건강기능식품 수입신고 대행·행정사 선택 기준 (서울·경기 지방식약청 영업등록·수입신고)",
      "href": "/blog/health-food-select"
    }
  ],
  "/services/hostel": [
    {
      "title": "호스텔업 등록 대행·행정사 선택 기준 (서울·경기 시·군·구청 사업계획 승인·등록)",
      "href": "/blog/hostel-select"
    }
  ],
  "/services/venture-cert": [
    {
      "title": "이노비즈 재신청 방법과 선정 탈락·공고 확인 시 대응 (기술혁신형 중소기업)",
      "href": "/blog/innobiz-cert-fix"
    },
    {
      "title": "이노비즈 인증 대행·행정사 선택 기준과 견적·상담 시 확인할 점 (기술혁신형 중소기업 선정)",
      "href": "/blog/innobiz-cert-select"
    },
    {
      "title": "벤처 인증 재신청과 확인 취소·유효기간 만료 시 대응 (벤처기업 확인)",
      "href": "/blog/venture-cert-fix"
    },
    {
      "title": "벤처기업 인증(확인) 대행·행정사 선택 기준과 견적·상담 시 확인할 점",
      "href": "/blog/venture-cert-select"
    }
  ],
  "/services/logistics": [
    {
      "title": "무등록 국제물류주선업 처벌·3년 신고 안 하면·변경등록 과태료·사업정지 등록취소",
      "href": "/blog/international-logistics-fix"
    },
    {
      "title": "국제물류주선업 등록 대행·행정사 선택 기준 (서울·경기 시·도 관할)",
      "href": "/blog/international-logistics-select"
    }
  ],
  "/services": [
    {
      "title": "인허가 없이 영업 처벌·무허가 영업 벌금·인허가 반려 대응·폐업신고 인허가 말소 정리",
      "href": "/blog/license-common-fix"
    }
  ],
  "/services/location-based-service": [
    {
      "title": "위치기반서비스 미신고 처벌·과태료·휴업 폐업 신고 정리",
      "href": "/blog/location-based-service-fix"
    },
    {
      "title": "위치기반서비스사업 신고 대행·행정사 선택 기준 (서울·경기 구분 없는 방송미디어통신위원회 신고)",
      "href": "/blog/location-based-service-select"
    }
  ],
  "/services/medical-device": [
    {
      "title": "의료기기 수입업 허가 취소·영업정지 사유와 거짓 허가 처벌 정리",
      "href": "/blog/medical-device-fix"
    },
    {
      "title": "의료기기 수입허가 대행·행정사 선택 기준 (서울·경기 수입업소 관할 지방식약청)",
      "href": "/blog/medical-device-select"
    }
  ],
  "/services/nonprofit": [
    {
      "title": "사단법인 설립허가 취소 사유·주무관청 검사 감독·과태료 정리 (민법 비영리법인)",
      "href": "/blog/nonprofit-fix"
    },
    {
      "title": "비영리사단법인 설립 대행·행정사 선택 기준 (서울·경기 주무관청 허가와 설립등기)",
      "href": "/blog/nonprofit-select"
    }
  ],
  "/services/procurement": [
    {
      "title": "부정당업자 제재 대응 — 입찰 참가자격 제한 사유·기간·과징금 대체·이의 절차 정리",
      "href": "/blog/procurement-fix"
    },
    {
      "title": "나라장터 등록 대행·행정사 선택 기준 (조달청 전자조달시스템 이용자등록, 서울·경기 구분 없음)",
      "href": "/blog/procurement-select"
    }
  ],
  "/services/rnd-support": [
    {
      "title": "연구비 부정사용 제재·정부과제 최종평가 실패 시 참여제한과 연구개발비 환수 정리",
      "href": "/blog/rnd-support-fix"
    },
    {
      "title": "정부 R&D 지원사업 신청 대행·행정사 선택 기준과 상담 시 확인할 점 (사업계획서 작성 대행 범위)",
      "href": "/blog/rnd-support-select"
    }
  ],
  "/services/sports-club": [
    {
      "title": "지정스포츠클럽 지정 취소 사유·스포츠클럽 등록 취소·유효기간 갱신 정리",
      "href": "/blog/sports-club-fix"
    },
    {
      "title": "지정스포츠클럽 지정 대행·행정사 선택 기준과 스포츠클럽 등록 대행 (서울·경기 시·군·구 등록 후 문체부 지정)",
      "href": "/blog/sports-club-select"
    }
  ],
  "/services/tobacco": [
    {
      "title": "무등록 담배 판매 처벌·담배수입판매업 등록 취소·영업정지 사유 정리",
      "href": "/blog/tobacco-fix"
    },
    {
      "title": "담배수입판매업 등록 대행·행정사 선택 기준 (서울·경기 본점 소재지 시·도지사)",
      "href": "/blog/tobacco-select"
    }
  ],
  "/services/urban-guesthouse": [
    {
      "title": "도시민박업 불법 숙박 처벌·위반건축물·폐업 신고 문제 해결 (오피스텔 에어비앤비 포함)",
      "href": "/blog/urban-guesthouse-fix"
    },
    {
      "title": "외국인관광 도시민박업 등록 대행·행정사 선택 기준 (서울·경기 지역 관할 포함)",
      "href": "/blog/urban-guesthouse-select"
    }
  ],
  "/services/women-enterprise": [
    {
      "title": "여성기업 확인 대행·행정사 선택 기준과 견적·상담 시 확인할 점 (여성기업 확인서 신청)",
      "href": "/blog/women-enterprise-select"
    }
  ]
}
